name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifact
        run: ./gradlew build

      - name: Publish artifact
        run: ./gradlew publishPlugins
        env:
          ORG_GRADLE_PROJECT_signingKey:            "${{ secrets.XPDUSTRY_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword:       "${{ secrets.XPDUSTRY_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_pluginPortalApiKey:    "${{ secrets.XPDUSTRY_GRADLE_PORTAL_KEY }}"
          ORG_GRADLE_PROJECT_pluginPortalApiSecret: "${{ secrets.XPDUSTRY_GRADLE_PORTAL_SECRET }}"
